name: ed_dt
channels:
  - conda-forge
dependencies:
  - joblib=1.1.0
  - jupyterlab=3.2.8
  - jupyterlab-spellchecker=0.7.2
  - matplotlib=3.5.1
  - numpy=1.22.1
  - pandas=1.4.0
  - pip=21.3.1
  - python=3.8.12
  - scipy=1.7.3
  - simpy=4.0.1
  - streamlit=1.4.0


